### ISSUE TITLE
Bin: batch input

### ISSUE THREAD

**Issue by fulldecent** [remusao/tldts#1009]
For the command line program, please consider to accept inputs from STDIN.

Then it would process each result, outputting the JSON to STDOUT.

The `jq` command can already handle a stack of JSONS concatenated together like this.

**Comment by remusao** [comment]
Hey @fulldecent,

Good idea! I might not have time to add this in in the near future, but if you would be willing to contribute, I'd be happy to review a PR to make this change. I think the only file hat needs to be changed is this one: https://github.com/remusao/tldts/blob/master/packages/tldts/bin/cli.js

Let me know if that's something you'd like to contribute,
Best,

**Comment by fulldecent** [comment]
Thank you for the invitation. Yes, implemented here:

https://github.com/remusao/tldts/pull/1021

**Comment by remusao** [comment]
Thanks for your contribution @fulldecent! The PR has been released as [v5.7.22](https://github.com/remusao/tldts/releases/tag/v5.7.22).
