### ISSUE TITLE
`domain.com.ru` will be detected its suffix as `.ru`, but shall be `.com.ru`

### ISSUE THREAD

**Issue by xiaohuilam** [remusao/tldts#1084]
see https://github.com/publicsuffix/list/blob/bc5d64dec327ab313126abf9eaed8d74e13d231e/public_suffix_list.dat#L11723

**Comment by remusao** [comment]
Hi @xiaohuilam,

This `.com.ru` suffix is part of the ["private section"](https://github.com/publicsuffix/list/blob/bc5d64dec327ab313126abf9eaed8d74e13d231e/public_suffix_list.dat#L10634) of the public suffix list, which is disabled by default in `tldts` to prevent surprises (having this behavior by default leads to lots of unexpected cases for users of the library).

You can [enable it](https://github.com/remusao/tldts/blob/master/packages/tldts/README.md#api) like so to get the results you expect:
```js
const { parse } = require('tldts');

console.log(
  parse('domain.com.ru', {
    allowPrivateDomains: true,
  }),
);

// Result:
// {
//   domain: 'domain.com.ru',
//   domainWithoutSuffix: 'domain',
//   hostname: 'domain.com.ru',
//   isIcann: false,
//   isIp: false,
//   isPrivate: true,
//   publicSuffix: 'com.ru',
//   subdomain: ''
// }
```

**Comment by xiaohuilam** [comment]
Thank you!
