### ISSUE TITLE
Underscore domain parsing

### ISSUE THREAD

**Issue by Mizzick** [remusao/tldts#1229]
Parsing an underscore domain appears to be wrong, eg

```
import { parse } from 'tldts';

const tldResult = parse(`https://_.rocks/iqadcontroller.js`);

// tldResult.domain is null
// tldResult.hostname is null

```

**Comment by remusao** [comment]
Hi @Mizzick, thanks for reaching out.

It seems like `_` cannot constitute a valid domain label on its own. If you want you can ask `tldts` to not validate the hostnames it extracts by specifying an optional second argument with the `validateHostname: false` option.

```typescript
import { parse } from 'tldts';

const tldResult = parse(`https://_.rocks/iqadcontroller.js`, {
  validateHostname: false,
});

// tldResult.domain is '_.rocks'
// tldResult.hostname is '_.rocks'
// tldResult.publicSuffix is 'rocks'
```

I hope this helps.

**Comment by remusao** [comment]
Closing this, please reopen if there are further comments or questions.

**Comment by shiny** [comment]
@remusao 
In ACME schema ([RFC5888](https://www.rfc-editor.org/rfc/rfc8555.html#section-8.4)), underscore is a part of DNS challenge domain name.
e.g. when validating `www.example.org`, we should set a txt record for `_acme-challenge.www.example.org`

but tldts think that's not a valid hostname ☹️
`npx tldts _acme-challenge.www.example.org`

```javascript
{
  "domain": null,
  "domainWithoutSuffix": null,
  "hostname": null,
  "isIcann": null,
  "isIp": false,
  "isPrivate": null,
  "publicSuffix": null,
  "subdomain": null
}
```

**Comment by remusao** [comment]
@shiny I think a host label cannot start with an `_` (I'd need to double-check to be sure); but if this is DNS-specific, the best might be to strip the leading `_` before passing the input to tldts.
