### ISSUE TITLE
Unable to parse wildcard subdomain

### ISSUE THREAD

**Issue by SpencerWoo** [remusao/tldts#1246]
```
> const { parse } = require('tldts');
undefined
> parse('*.google.com')
{
  domain: null,
  domainWithoutSuffix: null,
  hostname: null,
  isIcann: null,
  isIp: false,
  isPrivate: null,
  publicSuffix: null,
  subdomain: null
}
```

I've seen https://github.com/remusao/tldts/issues/134 however I was expecting this example to work.  

Can someone provide an example of a valid use of wildcards with this library?  I haven't investigated yet but I'm assuming I'm just missing something simple so any clarification would be appreciated -- thanks!

**Comment by remusao** [comment]
Hi @SpencerWoo,

Thanks for reaching out. I suspect that this comment might be useful: https://github.com/remusao/tldts/issues/1229#issuecomment-1008029281

In a nutshell, `*.google.com` is a valid public suffix rule, but not a valid hostname. And the `parse` method will by default make sure that the input is a valid hostname by default. If you want to disable this behavior, you can use the option below:

```js
> const { parse } = require('tldts');
undefined
> parse('*.google.com', {
  validateHostname: false,
})
```

Let me know if this helps.

**Comment by remusao** [comment]
Closing this, please reopen if there are further comments or questions.
