### ISSUE TITLE
parse of text 'arguments.constructor' crashes module

### ISSUE THREAD

**Issue by ishankaru** [remusao/tldts#129]
Issue:
Module crashes when 'arguments.constructor' is passed as a value to the parse() method
Example strings:
arguments.constructor
http://arguments.constructor
http://arguments.constructor/hello.html
http://www.arguments.constructor/hello.html

Version:
NodeJS: 10 and 11(current)
tldts:  4.0.6
OS: Windows 10

Test Application Source:
`const tldts = require('tldts');

let result = tldts.parse(process.argv[2]);

console.log(`domain:${result.domain}`);
console.log(`hostname:${result.hostname}`);
console.log(`isIcann:${result.isIcann}`);
console.log(`isIp:${result.isIp}`);
console.log(`isPrivate:${result.isPrivate}`);
console.log(`publicSuffix:${result.publicSuffix}`);
console.log(`subdomain:${result.subdomain}`);

**Test with Successful Run**
C:\tldtest>node tldtstest.js https://github.com/remusao/tldts
domain:github.com
hostname:github.com
isIcann:true
isIp:false
isPrivate:false
publicSuffix:com
subdomain:
![image](https://user-images.githubusercontent.com/16630297/56460329-1d8fe500-636f-11e9-9a64-e57f5ff6d675.png)

**Test to reproduce error:**
C:\tldtest>node tldtstest.js https://arguments.constructor/remusao/tldts
`C:\tldtest\node_modules\tldts\dist\tldts.cjs.js:277
        node = node[parts[index]] || node['*'];
                   ^

TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them
    at lookupInTrie (C:\tldtest\node_modules\tldts\dist\tldts.cjs.js:277:20)
    at suffixLookup (C:\tldtest\node_modules\tldts\dist\tldts.cjs.js:293:24)
    at getPublicSuffix (C:\tldtest\node_modules\tldts\dist\tldts.cjs.js:196:21)
    at parseImpl (C:\tldtest\node_modules\tldts\dist\tldts.cjs.js:243:30)
    at Object.parse (C:\tldtest\node_modules\tldts\dist\tldts.cjs.js:315:12)
    at Object.<anonymous> (C:\tldtest\tldtstest.js:3:20)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)`
![image](https://user-images.githubusercontent.com/16630297/56460325-12d55000-636f-11e9-8dbd-3ec9a82e8c88.png)

**Comment by remusao** [comment]
Hi @ishankaru and sorry for the late reply.

This issue seems to be caused by strict mode, which forbids accessing some properties on `object` instances (which tldts uses extensively to implement the Trie allowing suffix look-ups). It seems it can be disabled everywhere unless if the code is structured as an es6 module, in which case `strict mode` is enabled by default. I will think about how this particular issue can be solved. Thanks a lot for taking the time to report this.

Rémi

**Comment by remusao** [comment]
@ishankaru, The [v5](https://github.com/remusao/tldts/releases/tag/v5.0.0) of `tldts` was just published and should address the issue you reported. I've added [extensive tests](https://github.com/remusao/tldts/blob/master/test/tld.test.ts#L67) to cover the examples you gave as well as similar cases. I can also confirm that the examples work as far as I can tell:

```js
$ npx tldts http://arguments.constructor
{
  "domain": "arguments.constructor",
  "hostname": "arguments.constructor",
  "isIcann": false,
  "isIp": false,
  "isPrivate": false,
  "publicSuffix": "constructor",
  "subdomain": ""
}
```

```js
$ npx tldts http://arguments.constructor/hello.html
{
  "domain": "arguments.constructor",
  "hostname": "arguments.constructor",
  "isIcann": false,
  "isIp": false,
  "isPrivate": false,
  "publicSuffix": "constructor",
  "subdomain": ""
}
```

```js
$ npx tldts http://www.arguments.constructor/hello.html
{
  "domain": "arguments.constructor",
  "hostname": "www.arguments.constructor",
  "isIcann": false,
  "isIp": false,
  "isPrivate": false,
  "publicSuffix": "constructor",
  "subdomain": "www"
}
```

I will mark this issue as `closed` but feel free to re-open it or comment if you still encounter any issue.
