### ISSUE TITLE
Wildcards can occur for any segment, not just the start, and multiply

### ISSUE THREAD

**Issue by quasicomputational** [remusao/tldts#134]
The PSL's spec says:

> Wildcards are not restricted to appear only in the leftmost position, but they must wildcard an entire label. (I.e. *.*.foo is a valid rule: *bar.foo is not.)

...but the parsing code only looks for a single wildcard in the leftmost position:

https://github.com/remusao/tldts/blob/e7c140ce33444bf325298cf2e257f6d8a7958549/bin/parser.js#L32

There aren't actually any present rules that have a non-leftmost wildcard, so this is a future-proofing concern.

**Comment by remusao** [comment]
Hi @quasicomputational

We used to support wildcards in any position but following up on this discussion on the official project: https://github.com/publicsuffix/list/issues/145#issuecomment-366447410 it appears that the current agreement is to only support wildcards at the last position (and official documentation is yet to be updated with this change). Ultimately, this also allows for more efficient matching. It would be pretty easy to support it again though, but it does not seem like it's happening for now.

Best,
Rémi

**Comment by quasicomputational** [comment]
Oh, I see. I wish I'd noticed that issue before I wrote any code that has to deal with wildcards in the suffix, rather than after!

**Comment by remusao** [comment]
No worries, happy I could help. Could you maybe edit the description of your other issue https://github.com/publicsuffix/list/issues/806 to reflect the status of this one?
