### ISSUE TITLE
Returns incorrect results for localhost

### ISSUE THREAD

**Issue by AlyCode** [remusao/tldts#1415]
`getSubdomain('test.localhost')` returns `''` when it should return `'test'`

**Comment by remusao** [comment]
Hi @AlyCode,

Thanks for reaching out! The localhost case is tricky and needs to be handled with the following: https://github.com/remusao/tldts/blob/master/packages/tldts/README.md#retrieving-subdomain-of-localhost-and-custom-hostnames

I hope that helps,
