### ISSUE TITLE
Doesnt parse domains with leading special chars

### ISSUE THREAD

**Issue by piboistudios** [remusao/tldts#1534]
Related to #1523 

As an example, this will not parse IPFS DNSLink domain records names. This led to some obscure errors and a few hours of debugging my own code to figure out my code was not the problem, and unfortunately will lead to me opting to use `parse-domains` over `tldts` (which is a little cumbersome, as I was already using `tldts` quite generously)

DNS names allow leading underscores and dashes. They didn't originally, but the spec was updated to allow for this (hence, IPFS employs a DNSLink TXT record with a subdomain prefix `_dnslink`)

**Comment by remusao** [comment]
Hey, @piboistudios,

Thanks for reaching out! Seems like that is a recurrent issue lately so I will look at addressing this soon. Could you share a few examples of IPFS DNSLink domain records? I would love to add them to the tests.

best,

**Comment by bryanjswift** [comment]
> Thanks for reaching out! Seems like that is a recurrent issue lately so I will look at addressing this soon. Could you share a few examples of IPFS DNSLink domain records? I would love to add them to the tests.

I don't know about IPFS DNSLink domain records but `_0f6879f07aa61fc09d9645cce98b30e3.bsg-1418.bryanjswift.com`, which is a record name from AWS Certificate Validation fails to parse, as well as `_bsg-1418.bryanjswift.com` and `_bryanjswift.com`. It seems like a leading `_` should be permitted on subdomain values but not on apex domains names based on anecdotal testing (in other words I have not investigated the spec).

**Comment by remusao** [comment]
@bryanjswift @piboistudios A [new release](https://github.com/remusao/tldts/releases/tag/v6.0.0) contains some fixes which I think will address the issues reported in this issue. Please let me know if that works for you.

**Comment by bryanjswift** [comment]
> @bryanjswift @piboistudios A [new release](https://github.com/remusao/tldts/releases/tag/v6.0.0) contains some fixes which I think will address the issues reported in this issue. Please let me know if that works for you.

Thanks for the update! The team I am working with should be testing it out this week.
