### ISSUE TITLE
generate non-private subset

### ISSUE THREAD

**Issue by paulirish** [remusao/tldts#1881]
(First off, your library is EXACTLY what [we](https://github.com/GoogleChrome/lighthouse/pull/15641) were looking for. Many folks have a PSL distribution on npm, but you've done awesome work here. Thank you!)

The PSL has all its public ICANN domains and then at the bottom a bunch of PRIVATE domains.

![image](https://github.com/remusao/tldts/assets/39191/c81fd948-cde8-496b-8b8f-9c5d04b986c4)

For our uses, we don't care about the private domains, as we just need the PSL for improved URL parsing/display for the publically accessible web.   Also, we're very bundle size conscious. (So we appreciate the trie!)  Publishing an icann-only subset (or whatever you want to name it) would be super helpful.

Here's an initial idea of the size difference:
<img width="1187" alt="image" src="https://github.com/remusao/tldts/assets/39191/b4bf5887-f90e-48c8-a914-0b01c2bf0f30">

cc @alexnj

**Comment by remusao** [comment]
Hi @paulirish,

Thanks for reaching out, and for the kind words. I am happy that tldts is useful to you.

I have created a PR with preliminary work to create a separate `tldts-icann` which only contains the ICANN section: https://github.com/remusao/tldts/pull/1888

I'll have another look tomorrow but it's looking pretty good:

  - minified: 72K
  - gzipped (`--best`): 28K
  - brotli (`-q 11`): 24K
  - zstd (`--ultra -22`): 26K

I hope that helps,

**Comment by remusao** [comment]
You can find the new package here: https://www.npmjs.com/package/tldts-icann

**Comment by paulirish** [comment]
huge. thank you!
