### ISSUE TITLE
`parse` with only selected fields

### ISSUE THREAD

**Issue by SukkaW** [remusao/tldts#2050]
In my use case, I only want to get the `domain` and the `subdomain` of a domain.

I can simply do `tldts.getDomain()` and then `tldts.getSubdomain()`, but the input domain would be parsed twice.

Under the hood, `tldts-core` does have `FLAG` constants, but it is not exposed to the `tldts`. On the other hand, the `suffixLookup` function is not exported so I can't build my own `parseDomainAndSubdomain` on `tldts-core` directly.

**Comment by remusao** [comment]
Hi @SukkaW,

At the moment this is not possible but I wanted to point out that in your use-case, the only overhead you have is the [call to `getDomainWithoutSuffix`](https://github.com/remusao/tldts/blob/619f9980be1af820cc8bec6205ef118adbfda39e/packages/tldts-core/src/factory.ts#L154) which consist in a single [call to `.slice`](https://github.com/remusao/tldts/blob/082aa15f8375f4c4f4b022eafd67b54f499e94e3/packages/tldts-core/src/domain-without-suffix.ts#L13). This should be very fast and low-overhead. Is that a problem for your use-case?

Best,

**Comment by SukkaW** [comment]
@remusao 

If I call both `getDomain` and `getSubdomain` on the same domain, anything before `FLAG.SUB_DOMAIN` will be called twice:

- extractHostname & isValidHostname (though I actually disabled `extractHostname` for faster processing)
- isIp (though I actually disabled `detectIp` for faster processing)
- isValidHostname
- suffixLookup

> At the moment this is not possible but I wanted to point out that in your use-case, the only overhead you have is the [call to `getDomainWithoutSuffix`](https://github.com/remusao/tldts/blob/619f9980be1af820cc8bec6205ef118adbfda39e/packages/tldts-core/src/factory.ts#L154) which consist in a single [call to `.slice`](https://github.com/remusao/tldts/blob/082aa15f8375f4c4f4b022eafd67b54f499e94e3/packages/tldts-core/src/domain-without-suffix.ts#L13). This should be very fast and low-overhead. Is that a problem for your use-case?

Yes, replacing the `getDomain` and `getSubdomain` with one single `parse` call does improve the performance by about 30%, thanks!

**Comment by remusao** [comment]
Sounds good. I'll close this as resolved but feel free to open an issue if you'd need any other information of help.
