### ISSUE TITLE
BUG: Does not seem to be working for `www.expressl&t.net`

### ISSUE THREAD

**Issue by bhumijgupta** [remusao/tldts#604]
The library doesnot seem to extract tld for urls like `www.expressl&t.net`

**Comment by bhumijgupta** [comment]
P.S. I am using v5.6.25

**Comment by remusao** [comment]
Hey @bhumijgupta,

As far as I know `&` is not a valid character to be part of a hostname, and I think this is why `tldts` is rejecting it. You can ask `tldts` to not run hostname validation by providing an option:
```js
> tldts.parse('www.expressl&t.net', { validateHostname: false })
{
  domain: 'expressl&t.net',
  domainWithoutSuffix: 'expressl&t',
  hostname: 'www.expressl&t.net',
  isIcann: true,
  isIp: false,
  isPrivate: false,
  publicSuffix: 'net',
  subdomain: 'www'
}
```

I hope this helps,
Best

**Comment by bhumijgupta** [comment]
Thank you for the prompt reply. That would help a lot!
