### ISSUE TITLE
API additions

### ISSUE THREAD

**Issue by remusao** [remusao/tldts#9]
Consider the addition of the following in the API.

*Methods*:

- isPublicSuffix
- hasKnownSuffix
- isPrivate
- isIcann

*Attributes*:

- tld
- sld
- trd

Optionally we could also return:

 - scheme
- credentials
- port
- resource_path
- query_string
- fragment

**Comment by remusao** [comment]
Going to close this. The API is now pretty stable and there did not seem to be compelling reason to change that.

**Comment by Producdevity** [comment]
I know this has been closed for a while, but is there still a way to easily retrieve `sld`? Looking into migrating over from `psl`, but currently I don't see `sld` and something like `psl.isValid()` in the `tldts` docs.
