### ISSUE TITLE
org.ru not properly handled

### ISSUE THREAD

**Issue by jesec** [remusao/tldts#913]
Thanks for the library.

I am using tldts 5.7.2. (jesec/flood@861f3014)

I noticed a minor issue: `org.ru` is returned when getDomain is executed on `foo.bar.org.ru`. This is probably not the intended behavior.

`org.ru` is already in the public suffix list. 

Live example: https://runkit.com/embed/ppd53hwm7zba

**Comment by remusao** [comment]
Hi @jesec,

Thanks for taking the time to open an issue. This behavior is in fact correct but a bit obscure. There are two sections in the public suffix list: ICANN and PRIVATE. Enabling both by default has shown to yield counter-intuitive behaviors in the past and for this reason `tldts` only looks at ICANN if you don't specify any option. The `org.ru` suffix in in the PRIVATE section, and you can leverage it with the following option of `tldts`:
```javascript
const {getDomain} = require("tldts")

console.log(getDomain('a.b.org.ru', { allowPrivateDomains: true })); // bar.org.ru
```

If you'd like to check all the options available you can look at the following documentation which has more information: https://github.com/remusao/tldts/blob/master/packages/tldts/README.md#api

I hope that helps!
Best,
